### ISSUE TITLE
How to run the assembler EDASM?

### ISSUE THREAD

**Issue by PhilAndrew** [dgchurchill/nanowaspjs#1]
How to run... was it EDASM, I remember, on this? It used to be in rom, when I was 14... EDASM then I would try to turn on and off bits in the character mapping PCG

**Comment by dgchurchill** [comment]
Hi @PhilAndrew, the emulator at https://nanowasp.org is set up only with the BASIC ROM. If you want to run other programs then at the moment it's probably best to use a different emulator like ubee512. You can find information about it (along with a lot of other Microbee resources) in the forum and repositories at https://www.microbee-mspp.org.au.

If you just want to play around with PCG graphics again, then that is possible just using the BASIC ROM. Here's an example program from the Microbee documentation:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/883857/139178113-77c6bf04-21b7-4ebd-8619-3134f66db31c.png">

Text of the program is
```
DATA 1,2,2,4,4,8,8,16,17,34,36,72,80,160,192,0
DATA 128,64,64,32,32,16,16,8,136,68,36,18,10, 5,3,0
FOR I = 65040 TO 65071
  READ X
  POKE I,X
NEXT I
PCG
PRINT "ab"
NORMAL
```
which you should be able to enter into the emulator by first executing `AUTO` and then pasting the above text. Finally hit enter on a blank line and then `RUN` to execute it.
